apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nx-iot-core:view  
  namespace: nx-iot-core
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nx-iot-core:view 
  namespace: nx-iot-core
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nx-iot-core:view 
subjects:
- kind: Group
  name: "nx:nx-iot-core:view"
  apiGroup: rbac.authorization.k8s.io
