---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: nx-cluster-services
  name: nx-node-carer
spec:
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::ACCOUNT:role/nx-sre/k8s/pod/nx-platform-v1-STAGE/nx-node-carer-role-STAGE
    spec:
      serviceAccountName: nx-node-carer
      hostNetwork: false
      containers:
        - name: nx-node-carer
          image: 'ACCOUNT.dkr.ecr.eu-central-1.amazonaws.com/nexxiot.com/sre/k8s/nx-node-carer:STAGE'
          ports:
          - containerPort: 8000
          imagePullPolicy: Always
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: ROLE
            value: nx-node-carer-role-STAGE
