---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: nx-cluster-services
  name: nx-node-demoter
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: instance-retirement-service
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::ACCOUNT:role/nx-sre/k8s/pod/nx-platform-v1-STAGE/nx-node-demoter-role-STAGE
        spec:
          containers:
          - name: nx-node-demoter
            image: 'ACCOUNT.dkr.ecr.eu-central-1.amazonaws.com/nexxiot.com/sre/k8s/nx-node-demoter:STAGE'
