---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: nx-cluster-services
  name: nx-subject-mapper
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nx-subject-mapper 
        role: server
      annotations:
        iam.amazonaws.com/role: $ROLE
    spec:
      serviceAccountName: nx-subject-mapper
      containers:
        - name: nx-subject-mapper 
          image: subjectMapperImageName
          ports:
          - containerPort: 8000
          imagePullPolicy: Always
          env:
          - name: STAGE
            valueFrom:
              configMapKeyRef:
                name: cluster
                key: stage
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: cluster
                key: awsRegion
          - name: AWS_DEFAULT_REGION
            valueFrom:
              configMapKeyRef:
                name: cluster
                key: awsRegion
          - name: ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: cluster
                key: environment
          - name: CLUSTERNAME
            valueFrom:
              configMapKeyRef:
                name: cluster
                key: clusterName
            
---
apiVersion: v1
kind: Service
metadata:
  name: nx-subject-mapper
  namespace: nx-cluster-services
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "metric"
spec:
  ports:
  - name: metrics
    port: 8000
    protocol: TCP
    targetPort: 8000
  clusterIP: None
  selector:
    app: nx-subject-mapper
    role: server

---